id = "odin"
name = "Odin"
version = "0.3.11"
schema_version = 1
authors = ["Mo Nematzadeh <mohammad.h.nematzadeh@gmail.com>"]
description = "Odin support."
repository = "https://github.com/zed-extensions/odin"

[language_servers.ols]
name = "ols"
language = "Odin"

[grammars.odin]
repository = "https://github.com/NANDquark/tree-sitter-odin"
commit = "9bf0c800d51ed3d0e935aacd5c15a4eea990ffb8"

[debug_locators.odin-main]
